### ISSUE TITLE
数据集下载不了

### ISSUE THREAD

**Issue by chqiwang** [weiyinwei/GCN_PHR#5]
instagram数据集下载不了

**Comment by kbk12** [comment]
YFCC100M数据集也没找到

**Comment by weiyinwei** [comment]
您好，instagram数据集由于版权问题现在无法下载了，不好意思。
YFCC100M是公开数据集，可以找数据集拥有者直接下载。

**Comment by kbk12** [comment]
您好，您的推荐论文，我都看了，但是好多都找不到数据集，模型中YFCC100数据集,网上直接下载好多参数都对应不上，百忙之中，您可以发一下吗，做推荐太难了，好多模型都没有数据集，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiyinwei/PHR_GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiyinwei/PHR_GCN] 数据集下载不了 (#5)





 
您好，instagram数据集由于版权问题现在无法下载了，不好意思。
 YFCC100M是公开数据集，可以找数据集拥有者直接下载。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiyinwei** [comment]
推荐涉及用户的历史浏览记录，所以很多公司都非常介意公布。我自己也被警告过，所以现在不再直接发布数据集了，请见谅。

**Comment by kbk12** [comment]
老师，我是研一学生，您这篇论文Personalized Hashtag Recommendation for Micro-videos的一个作者是我的导师，数据集也不能分享一下吗。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiyinwei/PHR_GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiyinwei/PHR_GCN] 数据集下载不了 (#5)





 
推荐涉及用户的历史浏览记录，所以很多公司都非常介意公布。我自己也被警告过，所以现在不再直接发布数据集了，请见谅。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
